### PR TITLE
aodn/backlog#3048 - create snd survey method records on ingestion

### PR DESCRIPTION
**Pull request by jonescc**
Still need to add a test to verify survey not done survey methods added on ingestion.

### CODE REVIEW

**Review by nspool — APPROVED** [review]

**Comment by nspool** [comment]
@jonescc merge conflict

**Comment by jonescc** [comment]
> @jonescc merge conflict

I'll have to stop merging your PR's so I can get mine in ;-)

**Comment by jonescc** [comment]
Merge conflict fixed.

**Comment by jonescc** [comment]
OK need to fix test now.

**Review by nspool — APPROVED** [review]

**Pull request merged**
