### PR TITLE
 Select species by current name and total abundance

### PR DESCRIPTION
**Pull request by bpasquer**

### CODE REVIEW

**Comment by utas-raymondng** [comment]
@bpasquer I have rollback the change and look at the original sql in the getAllWithMethodForSites, there is a clause to skip item having supersededBy

"where m.method_id = :methodId AND site_raw.site_id IN (:siteIds) AND obsitem.superseded_by IS NULL "

**Comment by bpasquer** [comment]
> "where m.method_id = :methodId AND site_raw.site_id IN (:siteIds) AND obsitem.superseded_by IS NULL " hence the template should never show supersededBy entries.

Yes this clause is removing the superseded species, but what we are trying to achieve here is list superseding species with no observation attached, at that can only be achieved through  their related superseded species

**Comment by utas-raymondng** [comment]
@bpasquer I make couple of changes, and here is the template generated from my local PC, do you think the result correct?

image

[template(5).zip](https://github.com/aodn/nrmn-application/files/13855436/template.5.zip)

**Comment by bpasquer** [comment]
> @bpasquer I made couple of changes, and here is the template generated from my local PC, do you think the result correct?
> 
> image
> 
> [template(5).zip](https://github.com/aodn/nrmn-application/files/13855436/template.5.zip)

@utas-raymondng   the template has  the expected entries :+1:

**Comment by utas-raymondng** [comment]
@bpasquer so this PR contains your change right?

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Comment by utas-raymondng** [comment]
deployed to systest with Version 12.3 (854)

**Pull request merged**
