### PR TITLE
4710 fix error 404

### PR DESCRIPTION
**Pull request by utas-raymondng**

### CODE REVIEW

**Comment by nspool** [comment]
@utas-raymondng I think it's an error 400, not 404.

**Review by nspool — CHANGES_REQUESTED** [review]
If you encounter the constraint and error, return to the search and complete another correction the error message still shows. eg:

image

It would be good also if the error appears in an red outline alert to match other fatal messages.

**Comment by nspool** [comment]
@utas-raymondng build appears to be failing due to unused vars.

**Comment by utas-raymondng** [comment]
> @utas-raymondng build appears to be failing due to unused vars.

Yes, thanks for the remind. I am still in the mid of adding test case, so please ignore it for now.

**Pull request merged**
