### PR TITLE
Adjust schema for associations to reflect what should be sent/mark them

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Review by utas-tajona — APPROVED** [review]
LGTM

**Comment by jonescc** [comment]
So that doesn't work.  react form validates the request that its going to send against the schema.

Changing this to type = string format = uri

**Comment by jonescc** [comment]
We can use an array of strings to reflect that multiple uris can be submitted.

**Comment by jonescc** [comment]
Can now submit required uri to backend

**Review by utas-tajona — APPROVED** [review]
LGTM

**Pull request merged**
