### PR TITLE
Display required subset of observable item attributes in list view

### PR DESCRIPTION
**Pull request by jonescc**
Includes/requires  https://github.com/aodn/nrmn-application/pull/131

### CODE REVIEW

**Comment by jonescc** [comment]
Yes, can't leave pull requests too long.   I'll fix

**Comment by jonescc** [comment]
Conflicts resolved by revert

**Review by pmbohm — COMMENTED** [review]
User see 'Clazz' not 'Class' in list header

**Comment by jonescc** [comment]
> User see 'Clazz' not 'Class' in list header

I think that's an issue with the generic list code.  It doesn't look to be using the title defined in the json schema in preference to the attribute name.

**Comment by jonescc** [comment]
I guess I can change the json attribute name which makes sense - it doesn't need to be restricted by java identifier naming - so will do that.

**Comment by jonescc** [comment]
Fixed.

**Pull request merged**
