### PR TITLE
Hide the unresponsive filter icon (triangle) in the table header.

### PR DESCRIPTION
**Pull request by HavierD**
Issue [#5199](https://github.com/aodn/backlog/issues/5199)

### CODE REVIEW

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Comment by utas-raymondng** [comment]
Do not merge until  ticket on software upgrade merged
https://github.com/aodn/backlog/issues/5088

**Comment by HavierD** [comment]
> can you put the PR link back to the ticket? @HavierD
Yes I will. Sorry I did it at 11:00 and went to the kitchen. When i came back, I forgot updating the ticket :(

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Pull request merged**
