### PR TITLE
Validation move to backend, put back loading

### PR DESCRIPTION
**Pull request by utas-tajona**

### CODE REVIEW

**Review by jonescc — COMMENTED** [review]
Backend changes look good to me - just running it up to test...

**Review by nspool — APPROVED** [review]
Frontend looks good. @jonescc?

**Comment by jonescc** [comment]
Changes are working for me now.  @nspool any comments?

**Comment by jonescc** [comment]
Actually I can see you've approved so I'll just merge.

**Comment by nspool** [comment]
Went ahead and merged after seeing your comment :)

**Pull request merged**
