### PR TITLE
lowercase on groupby

### PR DESCRIPTION
**Pull request by utas-tajona**

### CODE REVIEW

**Comment by jonescc** [comment]
So do we still want to merge this or are we going to convert everything to lowercase when staging?  TBH - if case doesn't matter then keeping it consistently lower or uppercase in the system makes perfect sense to me.   @ccmoloney @bpasquer ?

**Comment by bpasquer** [comment]
We should keep the case insensitive lookups but for consistency SiteCodes,  Divers buddy and PQs initials and even Direction should be ingested in the DB as uppercase.

**Comment by jonescc** [comment]
> We should keep the case insensitive lookups but for consistency SiteCodes, Divers buddy and PQs initials and even Direction should be ingested in the DB as uppercase.

Probably should be to upper case anyway as that what  al the reference data is.   

Lets deal with it in a separate issue.

I'm happy to merge this one.

**Comment by jonescc** [comment]
Actually @utas-tajona - sounds like group by should be upper case.

**Comment by utas-tajona** [comment]
for the group by it shouldn't  matter

**Review by jonescc — APPROVED** [review]

**Pull request merged**
