### PR TITLE
Add custom list endpoint for site list view

### PR DESCRIPTION
**Pull request by jonescc**
spring data rest doesn't generate the correct metadata (json schema) for a spring data rest endpoint that uses excerpts or projections so just define it in a controller.

### CODE REVIEW

**Comment by jonescc** [comment]
For aodn/backlog#2582.   Note I have not included program in the projection as a program is not actually associated with a site.  

Waiting for clarification from @bpasquer on what to do about that.

**Comment by pmbohm** [comment]
@jonescc There is a conflict here

**Comment by jonescc** [comment]
Yep - no worries I need to clean up the code anyway.

**Comment by pmbohm** [comment]
@jonescc Rebase fixed now

**Comment by jonescc** [comment]
Adding a unit test

**Comment by jonescc** [comment]
Conflicts resolved by revert

**Pull request merged**
