### PR TITLE
Feature/survey validation ui

### PR DESCRIPTION
**Pull request by utas-tajona**
refactoring so the validation api call can return:
Every row with their errrors
list of global errors
input errors // if the  job isn't found

### CODE REVIEW

**Review by jonescc — COMMENTED** [review]
Looks good to me - some minor foirmatting/naming comments only

**Review by pmbohm — CHANGES_REQUESTED** [review]
Linting changes should not be part of this pull request and will cause massive merge conflicts if merged

**Comment by ccmoloney** [comment]
Is this ready for merging?  @utas-tajona

**Comment by utas-tajona** [comment]
splited in different PR

**Pull request closed without merging**
