### PR TITLE
adding delete rows API

### PR DESCRIPTION
**Pull request by utas-tajona**
adding the UI link soon

### CODE REVIEW

**Review by jonescc — COMMENTED** [review]
Just testing this and when I delete multiple rows using right click - delete selected row.  The rows appear to be deleted but when I validate most of them come back.  Looking at the requests sent to the backend - the same id is sent each time.

Also, this doesn't appear to be a 'Saveable' operation - the save button is not required to send delete operations to the backend.   Seems inconsistent to batch up some changes to save and not others.

**Comment by ccmoloney** [comment]
@utas-tajona Are you still working on this - or is it ready for re-review?

**Review by nspool — COMMENTED** [review]
Rows are deleting immediately from the DB. Should it wait until Save is pressed? Also Undo is not working for delete.

**Comment by ccmoloney** [comment]
I think we want deletes to only happen in the front-end until Save is invoked by the user.  Deleting rows should trigger the Save button to become active

**Review by ccmoloney — APPROVED** [review]

**Pull request merged**
