### PR TITLE
aodn/backlog#2730 - make surveyNum optional for ATRC method 0 & 10

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Review by nspool — CHANGES_REQUESTED** [review]
`RawValidation.toFormat` is not handling depth with only one component and is throwing a NullPointerException.

**Comment by jonescc** [comment]
> `RawValidation.toFormat` is not handling depth with only one component and is throwing a NullPointerException.

Thanks.  Didn't pick that up.

**Comment by jonescc** [comment]
Would have been a problem for RLS as well as survey number is not required for RLS.

**Comment by jonescc** [comment]
Should be OK now.

**Comment by nspool** [comment]
@jonescc still seeing a NullPointerException in RawValidation.toFormat. It appears that the Depth is not in the `values` dictionary.

**Comment by jonescc** [comment]
> @jonescc still seeing a NullPointerException in RawValidation.toFormat. It appears that the Depth is not in the `values` dictionary.

So not sure how you are getting the error.  I tested RLS and ATRC dept values without decimals in the UI.  How are you getting this to happen?

**Comment by nspool** [comment]
@jonescc if the sheet is valid.

**Comment by jonescc** [comment]
> @jonescc if the sheet is valid.

OK.  Now I understand.  Thanks!  Will look at this tommorrow morning.

**Comment by jonescc** [comment]
Actually - should be OK now.

**Comment by jonescc** [comment]
Note that there are other issues currently when a staged job is fully valid not related to this PR. (doesn't clear validation errors previously returned)

**Review by nspool — APPROVED** [review]

**Comment by jonescc** [comment]
https://github.com/aodn/backlog/issues/2920 raised for issue with validation results not being cleared

**Pull request merged**
