### PR TITLE
Display site validation errors on form

### PR DESCRIPTION
**Pull request by nspool**
http://nrmn-site-validation.dev.aodn.org.au/

### CODE REVIEW

**Comment by jonescc** [comment]
Need to update tests - build is failing

**Comment by nspool** [comment]
@jonescc will do.

**Review by jonescc — COMMENTED** [review]
Otherwise,  looks good!

**Comment by nspool** [comment]
Ready for review again @jonescc

**Review by jonescc — APPROVED** [review]

**Pull request merged**
