### PR TITLE
Survey API: Implement filters needed for corrections page

### PR DESCRIPTION
**Pull request by nspool**
The ugly casting appears to be necessary to work around null values being converted to type bytea. Please let me know if there is a better way of doing this.

### CODE REVIEW

**Review by utas-tajona — CHANGES_REQUESTED** [review]
looks good it just needs a test on the filter

**Comment by nspool** [comment]
@utas-tajona added tests however they are failing due to the fact that materialized view `ep_site_list` isn't populated. Leaving in but commented out for now.

**Comment by ccmoloney** [comment]
@bpasquer any thoughts on why ep_site_list wouldn't be populated?  @nspool you mean in the dev database?

**Comment by nspool** [comment]
@ccmoloney yes, in the db used for running the unit tests.

**Comment by bpasquer** [comment]
No no idea why it is not populated. Everything looks ok is nrmn_migration.

**Comment by ccmoloney** [comment]
We think it's something to do with how CJ has set up the unit tests to run.  It seems fine in nrmn_dev & nrmn_edge too.

**Review by utas-tajona — COMMENTED** [review]
LGTM

**Pull request merged**
