### PR TITLE
upload fix, measure visible in staged ag-grid

### PR DESCRIPTION
**Pull request by utas-tajona**

### CODE REVIEW

**Comment by jonescc** [comment]
Needs a rebase?   This branch is quite a few commits behind master,

**Review by jonescc — COMMENTED** [review]
Now displays measure values from the database where they match the column headings.  Looking at the data there is an issue with whats going into the database during ingestion where the incorrect measure is being put into the database.  I'll raise another issue.   Otherwise this LGTM

**Comment by jonescc** [comment]
Build issues!

**Comment by jonescc** [comment]
```
[INFO] /home/runner/work/nrmn-application/nrmn-application/ui/src/components/import/XlxsUpload.js
[INFO]   5:39  error  'Typography' is defined but never used  no-unused-vars
[INFO] 
[INFO] ✖ 1 problem (1 error, 0 warnings)**
```

**Comment by jonescc** [comment]
@nspool  any comments?  We have some outstanding issues with the ingestion process but I think these changes improve things so if the code's good we should merge.

**Review by nspool — APPROVED** [review]

**Comment by nspool** [comment]
@jonescc looks good.

**Pull request merged**
