### PR TITLE
Add more endpoints to share link feature

### PR DESCRIPTION
**Pull request by nspool**
Exports these endpoints by querying the view / materialized view, exports to CSV and uploads to S3.
Also removed the "disable" option from the `SharedLinkAdd` since now every extract should be available.

- EP_M2_INVERTS_ALL
- EP_M2_INVERTS_AUSTRALIA
- EP_M2_INVERTS_TAS
- EP_M2_INVERTS_NSW
- EP_M2_INVERTS_VIC
- EP_M2_INVERTS_WA
- EP_M2_INVERTS_SA
- EP_M2_INVERTS_NT
- EP_M2_INVERTS_QLD

### CODE REVIEW

**Comment by nspool** [comment]
EP_RARITY_ABUNDANCE
EP_SURVEY_LIST
EP_M0_OFF_TRANSECT_SIGHTING

**Comment by nspool** [comment]
EP_RARITY_ABUNDANCE
EP_RARITY_RANGE
EP_RARITY_EXTENTS

**Comment by nspool** [comment]
EP_M3_ISQ
 EP_M4_MACROCYSTIS_COUNT
 EP_M5_LIMPET_QUADRATS
 EP_M7_LOBSTER_COUNT

**Comment by nspool** [comment]
EP_M11_OFF_TRANSECT_MEASUREMENT
 EP_M12_DEBRIS
 EP_M13_PQ_SCORES
 EP_SPECIES_SURVEY_OBSERVATION

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Pull request merged**
