### PR TITLE
Improve Species Correction

### PR DESCRIPTION
**Pull request by nspool**
This is a significant rework of the Species Correction feature.

- Should now support pasting species name into filter
- Should Fix issues where filter fields need to be selected twice to "stick"
- Groups surveys IDs by Site (that can then be removed by site)

Workflow is broken up into 3 steps: Search, Correcting and Corrected, displayed as tabs at the top of the screen.

Start from the Search page on the first tab. Choose the species to correct using the filters. Click the row of the species to correct within that filter range to move to the second tab.

The second tab will display all sites matching the filtered region for this species, grouped by location. Click the `x` to remove a specific site or location from the correction. Choose the new species name from the dropdown at the top. And click Submit Correction.

On a successful correction the job view will be displayed as the third time. This lists the correction information including all the surveys updated. Either click the Return to Search button or the Search tab to correct another species.

### CODE REVIEW

**Comment by utas-raymondng** [comment]
1. Goto Species Correction page,
2. Type paste "Micromelo undatus" into the Species box, keep everything un-touch and then click search
3. The backend keep looping with messages

Hibernate: SELECT * FROM nrmn.observable_item_ref oi LEFT JOIN nrmn.lengthweight_ref lw ON (lw.observable_item_id = oi.observable_item_id) WHERE (? = TRUE OR oi.superseded_by IS NULL)  AND observable_item_name ILIKE '%' || ? || '%'  ORDER BY lower(observable_item_name) DESC  limit ?
Hibernate: SELECT * FROM nrmn.observable_item_ref oi LEFT JOIN nrmn.lengthweight_ref lw ON (lw.observable_item_id = oi.observable_item_id) WHERE (? = TRUE OR oi.superseded_by IS NULL)  AND observable_item_name ILIKE '%' || ? || '%'  ORDER BY lower(observable_item_name) DESC  limit ?
Hibernate: select secuser0_.id as id1_24_0_, secuser0_.email_address as email_ad2_24_0_, secuser0_.expires as expires3_24_0_, secuser0_.full_name as full_nam4_24_0_, secuser0_.hashed_password as hashed_p5_24_0_, secuser0_.status as status6_24_0_, secuser0_.version as version7_24_0_, roles1_.sec_user_id as sec_user1_26_1_, secrole2_.name as sec_role2_26_1_, secrole2_.name as name1_23_2_, secrole2_.version as version2_23_2_ from nrmn.sec_user secuser0_ left outer join nrmn.sec_user_roles roles1_ on secuser0_.id=roles1_.sec_user_id left outer join nrmn.sec_role secrole2_ on roles1_.sec_role_id=secrole2_.name where secuser0_.id=?
Hibernate: select secuser0_.id as id1_24_0_, secuser0_.email_address as email_ad2_24_0_, secuser0_.expires as expires3_24_0_, secuser0_.full_name as full_nam4_24_0_, secuser0_.hashed_password as hashed_p5_24_0_, secuser0_.status as status6_24_0_, secuser0_.version as version7_24_0_, roles1_.sec_user_id as sec_user1_26_1_, secrole2_.name as sec_role2_26_1_, secrole2_.name as name1_23_2_, secrole2_.version as version2_23_2_ from nrmn.sec_user secuser0_ left outer join nrmn.sec_user_roles roles1_ on secuser0_.id=roles1_.sec_user_id left outer join nrmn.sec_role secrole2_ on roles1_.sec_role_id=secrole2_.name where secuser0_.id=?
Hibernate: SELECT * FROM nrmn.observable_item_ref oi LEFT JOIN nrmn.lengthweight_ref lw ON (lw.observable_item_id = oi.observable_item_id) WHERE (? = TRUE OR oi.superseded_by IS NULL)  AND observable_item_name ILIKE '%' || ? || '%'  ORDER BY lower(observable_item_name) DESC  limit ?
Hibernate: SELECT * FROM nrmn.observable_item_ref oi LEFT JOIN nrmn.lengthweight_ref lw ON (lw.observable_item_id = oi.observable_item_id) WHERE (? = TRUE OR oi.superseded_by IS NULL)  AND observable_item_name ILIKE '%' || ? || '%'  ORDER BY lower(observable_item_name) DESC  limit ?

4. Then choose Aitutaki in Area/State
5. Click search again and no result return and keep searching

**Review by utas-raymondng — CHANGES_REQUESTED** [review]
Something wrong with backend during search

**Comment by nspool** [comment]
@utas-raymondng should be fixed now.

**Comment by utas-raymondng** [comment]
1. OK after you enter the above info on the first screen , "Micromelo undatus" and "Aitutaki", then click the "Aitutaki" text box again, you see the drop-down list value seems not correct.
2. If you continue to click search and select the "Micromelo undatus"
3. Type something that exist in the drop down
4. Then click on any area outside of the text box, the text gone and cannot click submit
5. If you select it from the drop down then you cannot un-select and choose other value.

**Comment by nspool** [comment]
CustomInputSearch component doesn't appear to work correctly in FireFox.

**Comment by nspool** [comment]
@utas-raymondng fixed autocomplete for FireFox. Ready for review again. Stack available at http://nrmn-aodnstack-nsp.dev.aodn.org.au/data/species

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Pull request merged**
