### PR TITLE
Agrid loading

### PR DESCRIPTION
**Pull request by pmbohm**
https://github.com/aodn/backlog/issues/2494

### CODE REVIEW

**Comment by utas-tajona** [comment]
since Ag grid is using most of the space we should use backdrop https://material-ui.com/components/backdrop/

**Comment by ccmoloney** [comment]
@pmbohm Build failing on this one

**Comment by ccmoloney** [comment]
@utas-tajona Would you be able to resolve the build issues with this one and merge it?

**Review by nspool — COMMENTED** [review]
The animation is working well, but it is only appearing once per page load. To demonstrate:
1. Set Throttling to "Slow 3G" in Chrome DevTools
1. Go to Diver. Loading Data appears as expected
1. Go to Location. Loading data does not appear
1. Going back to diver doesn't show the loading animation either.

**Comment by ccmoloney** [comment]
This will need to be resolved.

**Comment by ccmoloney** [comment]
Merging to get the functionality in the edge environment - but will raise an issue to fix the identified limitations.

**Pull request merged**
